name: 'EAS Build'
description: 'An action for handling logic when building with EAS'
inputs:
  platform:
    description: 'ios, android, or all'
    required: true
    default: 'all'
  profile:
    description: 'expo profile to use for build'
    required: true
    default: 'production'
  submit:
    description: 'flag for whether or not the build should be auto-submitted to app store/play store'
    required: true
    default: true

runs:
  using: "composite"
  steps:
    - run: eas build --platform ${{inputs.platform}} --profile ${{inputs.profile}} --non-interactive --no-wait --auto-submit
      if: ${{ inputs.submit == 'true' }}
      shell: bash
    - run: eas build --platform ${{inputs.platform}} --profile ${{inputs.profile}} --non-interactive --no-wait
      if: ${{ inputs.submit != 'true' }}
      shell: bash